from machine import Pin
import time
l1=Pin(5, Pin.OUT)
l2=Pin(14, Pin.OUT)
l3=Pin(18, Pin.OUT)
l4=Pin(19, Pin.OUT)
while True:
    l1.value(1)
    l2.value(0)
    l3.value(0)
    l4.value(0)
    time.sleep_ms(5)
    l1.value(0)
    l2.value(1)
    l3.value(0)
    l4.value(0)
    time.sleep_ms(5)
    l1.value(0)
    l2.value(0)
    l3.value(1)
    l4.value(0)
    time.sleep_ms(5)
    l1.value(0)
    l2.value(0)
    l3.value(0)
    l4.value(1)
    time.sleep_ms(5)
#Write your code here to run the stepper motor without using any loop
